//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public double VatPercentage { get; set; }
        public string Logo { get; set; }
        public string SaleLogo { get; set; }
        public string Favicon { get; set; }
        public int CurrencyPosition { get; set; }
        public string FooterText { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public int IsActive { get; set; }
    }
}
