//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Attendance = new HashSet<Attendance>();
            this.GoodsReceipt = new HashSet<GoodsReceipt>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long DesignationId { get; set; }
        public long DepartmentId { get; set; }
        public int RateType { get; set; }
        public string Phone { get; set; }
        public double HoureRateSalary { get; set; }
        public string Email { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public string Picture { get; set; }
        public long CountryId { get; set; }
        public long StateId { get; set; }
        public long CityId { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> TerritoryId { get; set; }
        public string CNIC { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public int IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceipt> GoodsReceipt { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Territories Territories { get; set; }
    }
}
