//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public long Id { get; set; }
        public long ExpenseTypeId { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public long PaymentAccount { get; set; }
        public long VNo { get; set; }
        public Nullable<System.DateTime> Deletedate { get; set; }
        public string Deleteuserid { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual ExpenseTypes ExpenseTypes { get; set; }
    }
}
