//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsReceipt()
        {
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetails>();
        }
    
        public long Id { get; set; }
        public long SupplierId { get; set; }
        public long PurchaseId { get; set; }
        public System.DateTime Date { get; set; }
        public double TotalQuantity { get; set; }
        public Nullable<long> EmployeenId { get; set; }
        public string Remarks { get; set; }
        public string JournalRemarks { get; set; }
        public string Reference { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceiptDetails> GoodsReceiptDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
