//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsIssueDetails
    {
        public long Id { get; set; }
        public long GoodsIssueId { get; set; }
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public long WarehouseId { get; set; }
        public string WarehouseName { get; set; }
    
        public virtual Warehouses Warehouses { get; set; }
        public virtual Products Products { get; set; }
        public virtual GoodsIssue GoodsIssue { get; set; }
    }
}
