//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsIssue()
        {
            this.GoodsIssueDetails = new HashSet<GoodsIssueDetails>();
        }
    
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long SaleId { get; set; }
        public System.DateTime Date { get; set; }
        public double TotalQuantity { get; set; }
        public Nullable<long> EmployeenId { get; set; }
        public string Remarks { get; set; }
        public string JournalRemarks { get; set; }
        public string Reference { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Sales Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsIssueDetails> GoodsIssueDetails { get; set; }
    }
}
