//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class stdfee1
    {
        public int VoucherID { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string FeeType { get; set; }
        public string AdmNo { get; set; }
        public string Student { get; set; }
        public string Father { get; set; }
        public string Paymentby { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string manualno { get; set; }
        public Nullable<int> FeeheadID { get; set; }
        public Nullable<int> PlusMinus { get; set; }
        public Nullable<int> yearid { get; set; }
        public Nullable<int> Sessionid { get; set; }
        public Nullable<int> sem { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string DDCheq { get; set; }
        public string UserID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
