//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentConcession
    {
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public int FeeheadID { get; set; }
        public Nullable<int> yearid { get; set; }
        public Nullable<int> sem { get; set; }
        public decimal Concession { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<System.DateTime> Edt { get; set; }
        public string ConcessionType { get; set; }
        public Nullable<int> Tariffid { get; set; }
        public string Remarks { get; set; }
        public string TariffSessionwiseid { get; set; }
    }
}
