//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertisingVedio
    {
        public int Id { get; set; }
        public string VedioUrl { get; set; }
        public string VedioDuration { get; set; }
        public string VedioTitle { get; set; }
        public bool status { get; set; }
    }
}
