//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatch
    {
        public int Id { get; set; }
        public string BatchName { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<long> MaxNoOfStudent { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
