//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassTeacherAllocation
    {
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> intEmpID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
