//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployyeMonthSalaryStructure
    {
        public int fldId { get; set; }
        public long salaryDetailId { get; set; }
        public Nullable<long> HeadId { get; set; }
        public string HeadAmount { get; set; }
        public string HeadType { get; set; }
        public string Salrytpe { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
