//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string Empcode { get; set; }
        public System.DateTime JoiningDt { get; set; }
        public int DeptID { get; set; }
        public int DesigID { get; set; }
        public int Qualification { get; set; }
        public double Experience { get; set; }
        public int StaffCategory { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public int GenderID { get; set; }
        public string UserID { get; set; }
        public string Pwd { get; set; }
        public int City { get; set; }
        public int State { get; set; }
        public int Country { get; set; }
        public string Pincode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PresentAddress { get; set; }
        public string PermAddress { get; set; }
        public int MaritalSatus { get; set; }
        public string AdharNo { get; set; }
        public int Religion { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Image { get; set; }
        public string BiometricID { get; set; }
        public bool Status { get; set; }
        public string PaymentMod { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string PFNo { get; set; }
        public string PANNO { get; set; }
        public string ESINO { get; set; }
        public string BankName { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
