//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeAccountInformation
    {
        public int Id { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> GradeId { get; set; }
        public string BankAccountName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string PfNo { get; set; }
        public string PanNo { get; set; }
        public string ESINo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool Status { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
