//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDocument
    {
        public int Id { get; set; }
        public Nullable<long> DocumentId { get; set; }
        public long EmployeeId { get; set; }
        public string DocImage { get; set; }
        public bool Status { get; set; }
    }
}
