//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExPayeeDetail
    {
        public int Id { get; set; }
        public string PayeeName { get; set; }
        public string CategoryId { get; set; }
        public Nullable<System.DateTime> PrimaryDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string TotalAmount { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public string PayingAmount { get; set; }
        public string DuesAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
