//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElearning
    {
        public int ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> AcademicYear { get; set; }
        public Nullable<int> Class { get; set; }
        public string subject { get; set; }
        public string teacher { get; set; }
        public string ChapterNo { get; set; }
        public string ChapterName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
