//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSalaryDetail
    {
        public int Id { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<long> GradeId { get; set; }
        public string MonthlyGross { get; set; }
        public string MonthlyDeduction { get; set; }
        public string GrossEarning { get; set; }
        public string GrossDeduction { get; set; }
        public Nullable<long> NoOfLeave { get; set; }
        public string NetSalary { get; set; }
        public Nullable<long> totalDayInMonth { get; set; }
        public Nullable<long> salayDayInMonth { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
