//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployeeLeaveRequest
    {
        public int Id { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> Department { get; set; }
        public Nullable<long> Designation { get; set; }
        public Nullable<long> LeaveType { get; set; }
        public Nullable<System.DateTime> StatDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> TakeLeaveCount { get; set; }
        public string Reason { get; set; }
        public Nullable<long> LeavStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
