//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeCalculate
    {
        public int fldId { get; set; }
        public Nullable<int> AcademicYear { get; set; }
        public string Months { get; set; }
        public Nullable<long> monthId { get; set; }
        public string monthlyAmount { get; set; }
        public string PaidAmount { get; set; }
        public string duesAmount { get; set; }
        public Nullable<long> fldstudentID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string discountPer { get; set; }
        public string discountAmnt { get; set; }
        public string ActualPayableAmnt { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<int> feePaid { get; set; }
        public Nullable<int> feeStructureID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> LateFeeFine { get; set; }
    }
}
