//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeConcession
    {
        public int RID { get; set; }
        public Nullable<int> TariffID { get; set; }
        public Nullable<int> FeeCategory { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> SchoolId { get; set; }
    }
}
