//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeStructureConfig
    {
        public long ID { get; set; }
        public long FeeCategory { get; set; }
        public string Amount { get; set; }
        public int FeeStructureID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<int> Academic_Year { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
