//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeHead
    {
        public int ID { get; set; }
        public string TariffName { get; set; }
        public Nullable<decimal> TariffPer { get; set; }
        public string Per { get; set; }
        public string Everyyear { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> Academic_Year { get; set; }
    }
}
