//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeStructureConfig2
    {
        public int ClassID { get; set; }
        public int BatchID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public byte YearID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<long> FeeCategory { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Stype { get; set; }
        public Nullable<int> Academicyear { get; set; }
        public Nullable<int> Ayid { get; set; }
        public int Coursefeeid { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
