//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGradeAssignSalaryHead
    {
        public int Id { get; set; }
        public Nullable<long> HeadId { get; set; }
        public Nullable<long> GradeId { get; set; }
        public string Amount { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string headType { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
