//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterGrade
    {
        public int Id { get; set; }
        public string GradeName { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
