//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblnewtimetable
    {
        public int ID { get; set; }
        public string SchoolID { get; set; }
        public string AcademicYear { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Subject { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string WeekDays { get; set; }
        public string TeacherID { get; set; }
        public string Status { get; set; }
        public string name { get; set; }
    }
}
