//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticeBoard
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string description { get; set; }
        public string userType { get; set; }
        public string NoticeFile { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
