//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScholarRegister
    {
        public long ID { get; set; }
        public string SRno { get; set; }
        public int StudentID { get; set; }
        public string WithdrawalNo { get; set; }
        public string TCNo { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
