//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuperAdminSubModule
    {
        public int ID { get; set; }
        public Nullable<int> SubModuleID { get; set; }
        public string SubModule { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
