//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentAttendence
    {
        public int AttendenceId { get; set; }
        public long StudentId { get; set; }
        public string AttendenceType { get; set; }
        public Nullable<System.DateTime> AttendenceDate { get; set; }
        public long TeacherId { get; set; }
        public Nullable<long> ClassId { get; set; }
        public long SectionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsBiometric { get; set; }
    }
}
