//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentdetailsClassToClass
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public string ClassID { get; set; }
        public string SectionID { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public Nullable<System.DateTime> PromotedDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Result { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string Academicyear { get; set; }
        public string Stream { get; set; }
    }
}
