//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLStudent
    {
        public int ID { get; set; }
        public string AcademicYear { get; set; }
        public string RegNo { get; set; }
        public string SRNo { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public int BatchID { get; set; }
        public int StreamID { get; set; }
        public string RollNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string BloodGroup { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> Religion { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string Languages { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CasteID { get; set; }
        public string AadharNo { get; set; }
        public string PermanentAddress { get; set; }
        public string CorrespondAddress { get; set; }
        public Nullable<decimal> PermPincode { get; set; }
        public string PermState { get; set; }
        public string PermCity { get; set; }
        public Nullable<decimal> CorsPincode { get; set; }
        public string CorsState { get; set; }
        public string CorsCity { get; set; }
        public string phone { get; set; }
        public string SMSmobileNo { get; set; }
        public string emailID { get; set; }
        public string FatherName { get; set; }
        public string FMobile { get; set; }
        public string FJob { get; set; }
        public Nullable<System.DateTime> FDOB { get; set; }
        public string FDesig { get; set; }
        public string FNationality { get; set; }
        public string FOfficeAddress { get; set; }
        public string Fmail { get; set; }
        public Nullable<int> FQualification { get; set; }
        public string FAdharNo { get; set; }
        public string MotherName { get; set; }
        public string Mmobile { get; set; }
        public string MJob { get; set; }
        public Nullable<System.DateTime> MDOB { get; set; }
        public string MDesig { get; set; }
        public string MNationality { get; set; }
        public string MOfficeAddress { get; set; }
        public string Mmail { get; set; }
        public Nullable<int> MQualification { get; set; }
        public string MAdharNo { get; set; }
        public string FIncome { get; set; }
        public string MIncome { get; set; }
        public string GuardianName { get; set; }
        public string Relation { get; set; }
        public Nullable<int> GQualification { get; set; }
        public string GJob { get; set; }
        public string GIncome { get; set; }
        public string GNationality { get; set; }
        public string GDesig { get; set; }
        public string Gmobile { get; set; }
        public string GOfficeAddress { get; set; }
        public string GAdharNo { get; set; }
        public string Gmail { get; set; }
        public string EmergencyNo { get; set; }
        public string EmerContPerson { get; set; }
        public string ContPersRelation { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string PicPath { get; set; }
        public string FPicPath { get; set; }
        public string MPicPath { get; set; }
        public string SUserID { get; set; }
        public string SPwd { get; set; }
        public string PUserID { get; set; }
        public string PPwd { get; set; }
        public Nullable<int> Status { get; set; }
        public int SchoolID { get; set; }
        public string PermCountry { get; set; }
        public string CorsCountry { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
        public string BiometricID { get; set; }
        public string GmailId { get; set; }
        public string GPassword { get; set; }
    }
}
