//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStRegDoc
    {
        public int ID { get; set; }
        public long StudentID { get; set; }
        public long DocID { get; set; }
        public string DocPath { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
