//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStRegPrevSchoolDet
    {
        public int ID { get; set; }
        public string PSYear { get; set; }
        public string School { get; set; }
        public string Board { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Marks { get; set; }
        public string TCNo { get; set; }
        public string Awards { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
