//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeTable
    {
        public long ID { get; set; }
        public Nullable<long> CTDet_ID { get; set; }
        public Nullable<long> CT_ID { get; set; }
        public Nullable<long> TimeTableID { get; set; }
        public string WeekDay { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
