//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskDetail
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public string TaskPriority { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> Department { get; set; }
        public Nullable<long> Employee { get; set; }
        public Nullable<long> classId { get; set; }
        public Nullable<long> SectionId { get; set; }
        public Nullable<long> Student { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
    }
}
