//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThoughtsOfDay
    {
        public int fldId { get; set; }
        public string Thoughts { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
