//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportVehicalDetail
    {
        public int Id { get; set; }
        public string VehicalNo { get; set; }
        public string TotalSeats { get; set; }
        public string AllowedSeats { get; set; }
        public string OwnershipType { get; set; }
        public string InsuranceDate { get; set; }
        public string PollutionDate { get; set; }
        public string TrackNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_on { get; set; }
        public string deletedby { get; set; }
        public string FitnessExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
