//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int ID { get; set; }
        public string EmpID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public int GenderID { get; set; }
        public int MaritalSatus { get; set; }
        public int Category { get; set; }
        public int Religion { get; set; }
        public int DeptID { get; set; }
        public int DesigID { get; set; }
        public int StaffCategory { get; set; }
        public int Grade { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime JoiningDt { get; set; }
        public int Qualification { get; set; }
        public double Experience { get; set; }
        public string PresentAddress { get; set; }
        public string PermAddress { get; set; }
        public int City { get; set; }
        public int State { get; set; }
        public int Country { get; set; }
        public decimal Pincode { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public decimal Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> AdharNo { get; set; }
        public string EmpType { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string BloodGroup { get; set; }
        public string PicPath { get; set; }
        public string UserID { get; set; }
        public string Pwd { get; set; }
        public string BiometricID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Signature { get; set; }
    }
}
