//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_MachineRawPunch
    {
        public int Tran_MachineRawPunchId { get; set; }
        public string CardNo { get; set; }
        public System.DateTime PunchDatetime { get; set; }
        public string P_Day { get; set; }
        public string ISManual { get; set; }
        public string PayCode { get; set; }
        public string MachineNo { get; set; }
    }
}
