//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public long Id { get; set; }
        public string VNo { get; set; }
        public string Vtype { get; set; }
        public System.DateTime VDate { get; set; }
        public long COAId { get; set; }
        public string COA { get; set; }
        public string Narration { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public bool IsPosted { get; set; }
        public bool IsAppove { get; set; }
        public bool IsOpening { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
