//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZommDetail
    {
        public long ZID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string MeetingID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> STime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertUserId { get; set; }



        public string Dt { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Subject { get; set; }
        public string Time { get; set; }
        public string Teacher { get; set; }
    }
}
